sonar.projectKey=CityOpz_frontend
sonar.organization=cityopz
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.ts,**/*.test.tsx,**/*.d.ts,**/routes.ts,**/pages/**,**/*Hero.tsx,**/*.types.ts,**/*.variants.ts,src/main.tsx,src/app/routes.ts,src/app/layouts/**,src/shared/lib/api/authInterceptor.ts,src/shared/components/ui/badge.tsx,src/shared/components/ui/card.tsx,src/shared/hooks/useDocumentTitle.ts,src/shared/theme/**,src/features/landing/**,src/features/admin/pages/DashboardPage.tsx,src/features/auth/pages/LogoutPage.tsx
sonar.sourceEncoding=UTF-8
